---
# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 The Linux Foundation <matthew.watkins@linuxfoundation.org>

name: "Nexus Upload"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Nexus Upload"
        uses: ModeSevenIndustrialSolutions/nexus-upload-action@v0.0.7
        with:
          nexus_server: nexus3.o-ran-sc.org
          nexus_username: admin
          nexus_password: ${{ secrets.nexus_password }} # Repository secret
          nexus_repository: datasets
          repository_format: raw # Optional
          file_extension: txt # Optional
          directory: files # Optional
